# Generated by Django 4.1 on 2022-08-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos'),
        ),
    ]
