# Generated by Django 4.1 on 2022-08-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0002_producto_descripcion_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
