# Generated by Django 4.1 on 2022-08-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0005_categorias_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='noticias')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
