# Generated by Django 4.1 on 2022-08-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0006_noticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='fecha',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
