# Generated by Django 4.1 on 2022-08-26 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0007_noticias_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Juegos.categorias'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
