# Generated by Django 4.1 on 2022-08-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0008_noticias_tipo_alter_noticias_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='autor',
            field=models.CharField(default='Administrador', max_length=60),
        ),
    ]
