# Generated by Django 4.1 on 2022-08-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0009_noticias_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
