# Generated by Django 4.1 on 2022-08-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0011_pedidos_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='detalle',
            field=models.TextField(default='Compra en línea'),
        ),
    ]
