# Generated by Django 4.1 on 2022-08-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0012_pedidos_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
